apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  labels:
    app: fiapchat
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fiapchat
  template:
    metadata:
      labels:
        app: fiapchat
    spec:
      containers:
        - name: fiapchat
          image: "tonanuvem/chat"
          ports:
            - name: http
              containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: chat-service
spec:
  selector:
    app: fiapchat
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 32100
  type: NodePort
