# https://github.com/ibm-developer/icp-nodejs-sample/blob/master/chart/ibm-nodejs-sample/values.yaml
# https://github.com/IBM/charts/tree/master/stable/ibm-nodejs-express

# Licensed Materials - Property of IBM
# (C) Copyright IBM Corp. 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

image:
  # Production image
  repository: ibmcom/icp-nodejs-sample
  tag: latest
  # tag: 8
  # tag: 10
  pullPolicy: Always
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
# This is important as the port must match what's in the Dockerfile and the listen server port
service:
  name: Node
  type: NodePort
  port: 3000
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 100m
